### ISSUE TITLE
reduceGraph doesn't update collection in store

### ISSUE THREAD

**Issue by skarm61** [satanTime/ngrx-entity-relationship#1612]
On page loading first I dispatch `loadMyFiles`, this effect executes and populates the store with original data.
When I unlink a file, I dispatch `unlinkMyFileSuccess`, the effect executes, it sends a request to the backend and received data but doesn't update the store with new data.
The new array of files is pretty similar to the original one, with the only difference in one file record - one or two fields disappear from one record. Not replaced with an undefined, affected object in an array of files is missing this property.

```
public readonly loadMyFiles$ = createEffect(() =>
    this.actions$.pipe(
      ofType(loadMyFiles, uploadFileSuccess, unlinkMyFileSuccess),
      switchMap(({ cid }) =>
        cidTask(
          cid,
          this.myLibraryFileService.getUploadedFiles().pipe(
            mergeMap((myLibraryFiles: Array<MyLibraryFile>) => [
              cidPayload({
                cid,
                payload: myLibraryFiles.map((myLibraryFile) => myLibraryFile.id),
              }),
              reduceGraph({
                data: myLibraryFiles,
                selector: cpSelectMyFiles,
              }),
            ]),
          ),
        ),
      ),
    ),
  );
```

**Comment by skarm61** [comment]
I've found the reason of issue and added test what covers this case
https://github.com/satanTime/ngrx-entity-relationship/pull/1613

**Comment by satanTime** [comment]
Hi @skarm61, unfortunately, your test doesn't reproduce the problem:

```ts
    it('removes old field from an existing entity', () => {
        const state = {
            entity1: {
                ids: ['1'],
                entities: {
                    1: {
                        rand: 'rand0',
                        old: true,
                    },
                },
            },
        };
        const state1 = {p: Math.random()};
        const entity = {
            id: '1',
            rand: 'rand1',
        };
        const selector = rootEntity<typeof state, any>(s => s.entity1);
        patchStateSpy.and.returnValues(state1);

        debugger;
        const actual = injectEntity.func(state, selector, entity);
        expect(actual).toBe(state1);
        expect(patchStateSpy).toHaveBeenCalledWith(
            state,
            state.entity1,
            jasmine.objectContaining({
                entities: {
                    1: {
                        id: '1',
                        rand: 'rand1',
                        old: true, // <- the part you forgot to add for assertion, with it your test is green.
                    },
                },
            }),
        );
    });
```

**Comment by satanTime** [comment]
Hi @skarm61,

as discussed in the chat, this is expected behavior and won't be changed.
The right fix here is to update your backend to return `old: undefined` or to patch the returned value after fetching data is to change backend isn't possible.

Consider it as `select id, rand, old from table`, you'll always get the `old` key even if its value is empty. Likewise, `select id, rand from table` doesn't mean that the value of the `old` key is empty.
