### ISSUE TITLE
"real usage example" links don't work.

### ISSUE THREAD

**Issue by jucasoft** [satanTime/ngrx-entity-relationship#301]
Hi,
in the README.md file, the "real usage example" links don't work.

**Comment by satanTime** [comment]
Hi @jucasoft,

ah, true! thanks! I'll fix it next days.

They are here now:
https://github.com/satanTime/ngrx-entity-relationship/tree/master/e2e/a11/src/app

**Comment by satanTime** [comment]
[v1.4.0](https://github.com/satanTime/ngrx-entity-relationship/releases/tag/v1.4.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.
