### ISSUE TITLE
many to many?

### ISSUE THREAD

**Issue by jucasoft** [satanTime/ngrx-entity-relationship#302]
Hello,
I have tried your library and it works perfectly.
https://ngrx-entity-relationship.herokuapp.com/user/main

I was looking for a solution for my project, it was not easy to find this library.

I did not understand if the library manages relations:
  - many to many
  - one to many

how do i associate the staff attribute?
```
export interface Company {
    id: string;
    name: string;

    staff?: Array<User>; <===== ?????????

    admin?: User;
    adminId?: string;

    address?: Address;
    addressId?: string;
}
```

**Comment by satanTime** [comment]
Hi again,

might you explain how you tried to search for it? I'll try to add suitable keywords to improve search appearance.

There are several options:

1. company should provide `staffId`.
```
export interface Company {
    id: string;
    name: string;

    staffId?: Array<string>;
    staff?: Array<User>; <===== ?????????

    admin?: User;
    adminId?: string;

    address?: Address;
    addressId?: string;
}

const companyWithEmployees = rootEntity(
    companySelector,
    relatedEntity(
        userSelector,
        'staffId',
        'staff',
    ),
);
```

2. user has `companyId`
```
export interface User {
    companyId?: string;
}

const companyWithEmployees = rootEntity(
    companySelector,
    childEntitySelector(
        userSelector,
        'companyId',
        'staff',
    ),
);
```

For many to many - might you provide your data structure and how you would like to select the records?
In my case I used `typeorm` and for such relationships it returns data like `staffId`.

**Comment by jucasoft** [comment]
I found you looking for the words "ngrx entity one to many":
https://stackoverflow.com/questions/61933118/ngrx-how-to-many-to-many-relationship-between-entities

I've been looking for weeks:
normalizing
https://redux.js.org/recipes/structuring-reducers/normalizing-state-shape
https://github.com/paularmstrong/normalizr

ngrx orm
https://gist.github.com/musou1500/6f7649bf230f1c7e06280b0103519b8b

**Comment by satanTime** [comment]
Aha, thanks.

I'll try promote ngrx orm and ngrx normalizing. For the last weeks I've been working on redux version, because of that, I think, the next update will be ready only in 2-3 weeks.

Btw, does the thing about many-to-may work for you?

**Comment by jucasoft** [comment]
hi,

Hi, I tried the implementation, but I have an error.

companyId successfully finds it in the User entity
https://github.com/jucasoft/ngrx-entity-crud-prime-ng-boilerplate/blob/a8e3103ef42d063c832d04e190de45c9dc629f79/src/app/main/models/vo/user.ts#L8

staff, does not find it in Compani (even if present) it seems to look for it in User.
https://github.com/jucasoft/ngrx-entity-crud-prime-ng-boilerplate/blob/a8e3103ef42d063c832d04e190de45c9dc629f79/src/app/root-store/company-store/selectors.ts#L29

**Comment by satanTime** [comment]
Yeah, my bad. Because it's an array not `childEntity`, but `childrenEntity` should be used.

```ts
const companyWithEmployees = rootEntity(
  selectState,
  childrenEntities(
    UserStoreSelectors.selectState,
    'companyId',
    'staff',
  ),
);
```

**Comment by satanTime** [comment]
another thing is that with the current approach it causes `Warning: Circular dependency detected:`.
It's quite common because of cross relationships.

it's caused by 
```ts
export const selectState: MemoizedSelector<object, State> = createFeatureSelector<State>(Names.NAME);
```
and
```ts
export const selectState: MemoizedSelector<object, State> = createFeatureSelector<State>(Names.NAME);
```

it should be in any other file, but not within `ngrx-entity-relationship` selectors.
I put them in the `state.ts` usually.

**Comment by jucasoft** [comment]
Resolved
