### ISSUE TITLE
Load entities with @ngrx/data requesting graphql server

### ISSUE THREAD

**Issue by vladimirdrayling** [satanTime/ngrx-entity-relationship#595]
This lib is awesome! Thank you!

Trying to load entities with @ngrx/data requesting a graphql server but don't know how to init the loading process. This isn't mentioned in the docs https://ngrx-entity-relationship.sudo.eu/guide/ngrx-data.

Basically I have configured @ngrx/data user service and user selector service.

How to call a graphql end point to get users using user selector service?

**Comment by satanTime** [comment]
Hi,

thanks for the feedback.

You might take a look at this project: https://github.com/satanTime/nx-nestjs-angular-graphql

It loads data via `GraphQL` via `@ngrx/effects`:
[effect](https://github.com/satanTime/nx-nestjs-angular-graphql/blob/master/apps/ct-frontend/src/app/entity/store/entity.effects.ts)
[caller](https://github.com/satanTime/nx-nestjs-angular-graphql/blob/master/apps/ct-frontend/src/app/entity/entity.component.ts#L61-L66)

I think, something similar can be done with `@ngrx/data`, how do you use `@ngrx/data` with `GraphQL` currently?

**Comment by vladimirdrayling** [comment]
[Repo](https://codesandbox.io/s/vd-ngrx-data-graphql-9utmp?file=/src/app/app.component.html) with short description in `app.component.html`.

### The main idea

of `@ngrx/data` is to abstract `CRUD` operations. I thought I could use `@ngrx/data` to load entities requesting a `graphql` server and use that abstraction. But it's not possible right now, coz [DefaultDataService](https://github.com/ngrx/platform/blob/a9e7fb177c4750ac5c8a39ea3898454669cde847/modules/data/src/dataservices/default-data.service.ts#L28) only supports [REST-y API](https://github.com/ngrx/platform/blob/a9e7fb177c4750ac5c8a39ea3898454669cde847/modules/data/src/dataservices/default-data.service.ts#L200).

I think, in order to use `@ngrx/data` with `graphql` I need to create custom `DefaultGraphqlService` & `DefaultGraphqlServiceFactory` with adjusted CRUD functionality that sends graphql requests. The only problem I currently see is the subscription. But at a first glance `rxjs/websocket` should solve the issue.

### Issue

I just don't wanna create the boilerplate with all the actions, selectors, services, reducers etc.

I'm trying to understand if it's possible not to use apollo-angular at all.

### Basic workflow

#### Setup

##### Import in `AppModule`

```ts
EntityGraphqlModule.forRoot(), // Maybe with some config `forRoot({ ... })`
```

##### Register entity
Either in `AppModule` or somewhere else lazily

#### Usage

Load entities

```ts
export class SomeComponent {
  constructor(public readonly someService: SomeService) {
    someService.load();
  }
}
```

#### Fetching

and in a `SomeComponent`

```html
<ul>
  <li *ngFor="let entity of someService.entities$ | ngrxPush">
    {{ entity.someProp }}
  </li>
</ul>
```

#### Mutating (create/update/upsert/delete)

continiuing in `SomeComponent`

```ts
create(entity: SomeEntity) {
  this.someService.create(entity);
}

update(entity: SomeEntity) {
  this.someService.update(entity);
}

upsert(entity: SomeEntity) { // The `id` of entity should be either empty or undefined
  this.someService.update(entity);
}

deleteById(id: string) {
  this.someService.delete(id);
}

deleteByEntity(entity: SomeEntity) {
  this.someService.delete(entity);
}

// etc
```

**Comment by satanTime** [comment]
I see. It isn't easy to answer it without investigation.

Based on my experience, I can say that a selector should be provided in order to use `ngrx-entity-relationship` to generate `GraphQL` queries. Therefore, at least 3 actions should be created: `create`, `update`, `delete` which accept an entity and a selector. Then a service could something like the [effect](https://github.com/satanTime/nx-nestjs-angular-graphql/blob/master/apps/ct-frontend/src/app/entity/store/entity.effects.ts).

**Comment by vladimirdrayling** [comment]
Agree. With the help of your selectors it's possible to create an abstraction with graphql CRUD functionality. I think I got the answer, thank you @satanTime!

Close for now.
